use elf::ElfBytes;
use elf::endian::AnyEndian;
use ld_so_cache::CacheEntry;
use ld_so_cache::parsers::parse_ld_cache;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use tracing::warn;

const LIBRARY_BLACKLIST: &str = include_str!("../appimage-excludelist");

pub fn copy_shared_libraries(elf: &Path, target_directory: &Path) -> anyhow::Result<()> {
    // Read the ld.so library cache generated by ldconfig
    let ld_cache_file = match fs::read("/etc/ld.so.cache") {
        Ok(ld_cache_file) => ld_cache_file,
        Err(e) => {
            warn!("Failed to read ld.so cache: {}", e);
            warn!("Libraries were unable to be copied. The bundle may be incomplete.");
            return Ok(());
        }
    };
    let ld_cache = parse_ld_cache(&ld_cache_file)?;
    let ld_cache = ld_cache.get_entries()?;

    let mut failed_libraries = HashMap::new();

    let mut dependents = vec![elf.to_owned()];
    let mut required_dependants = HashSet::new();

    let blacklisted_libraries = LIBRARY_BLACKLIST
        .lines()
        .filter(|line| !line.trim().is_empty() && !line.starts_with("#"))
        .collect::<Vec<_>>();

    while let Some(dependant) = dependents.pop() {
        let dynamic_dependencies = elf_dynamic_dependencies(
            &dependant,
            &ld_cache,
            &blacklisted_libraries,
            &mut failed_libraries,
        )?;
        dependents.extend(
            dynamic_dependencies
                .iter()
                .filter(|&dep| !required_dependants.contains(dep))
                .cloned(),
        );
        required_dependants.extend(dynamic_dependencies);
    }

    if !failed_libraries.is_empty() {
        for (library_name, failed_paths) in failed_libraries {
            warn!("Library {library_name} required, but not found in ld cache. Skipping.");
            for path in failed_paths {
                warn!("  Required by {path:?}");
            }
        }
        warn!(
            "The above libraries were required but could not be found. \
            The bundle may be incomplete."
        );
    }

    let mut have_error = false;
    for required_dependant in required_dependants {
        if let Err(e) = fs::copy(
            &required_dependant,
            target_directory.join(required_dependant.file_name().unwrap()),
        ) {
            have_error = true;
            warn!("Failed to copy shared library {required_dependant:?}: {e}");
        }
    }

    if have_error {
        warn!(
            "Some libraries could not be copied. \
            The bundle may be incomplete."
        );
    }

    Ok(())
}

fn elf_dynamic_dependencies(
    elf: &Path,
    ld_cache: &[CacheEntry],
    blacklisted_libraries: &Vec<&str>,
    failed_libraries: &mut HashMap<String, Vec<PathBuf>>,
) -> anyhow::Result<Vec<PathBuf>> {
    let file_data = fs::read(elf)?;
    let elf_file = ElfBytes::<AnyEndian>::minimal_parse(&file_data)?;

    let Some(dynamic) = elf_file.dynamic()? else {
        return Ok(vec![]);
    };

    let Some((_, string_table)) = elf_file.dynamic_symbol_table()? else {
        return Ok(vec![]);
    };

    let mut dependencies = Vec::new();
    for needed_line in dynamic
        .iter()
        .filter(|dyn_entry| dyn_entry.d_tag == elf::abi::DT_NEEDED)
    {
        let library_name = string_table.get(needed_line.d_val() as usize)?;
        if blacklisted_libraries.contains(&library_name) {
            continue;
        }

        let Some(ld_cache_entry) = ld_cache
            .iter()
            .find(|entry| entry.library_name == library_name)
        else {
            failed_libraries
                .entry(library_name.to_string())
                .or_default()
                .push(elf.to_owned());
            continue;
        };

        dependencies.push(PathBuf::from(ld_cache_entry.library_path.clone()));
    }

    Ok(dependencies)
}
