#!/bin/sh

export CNTP_RUNTIME_OLD_XDG_DATA_DIRS="$XDG_DATA_DIRS"
export CNTP_RUNTIME_OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export CNTP_RUNTIME_OLD_PATH="$PATH"

APPIMAGE_RELATIVE_BASE_DIR=$(dirname "$0")
APPIMAGE_BASE_DIR=$(realpath "$APPIMAGE_RELATIVE_BASE_DIR")
export XDG_DATA_DIRS="$APPIMAGE_BASE_DIR/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export LD_LIBRARY_PATH="$APPIMAGE_BASE_DIR/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PATH="$APPIMAGE_BASE_DIR/appimage_runtime/bin${PATH:+:$PATH}"

exec "$APPIMAGE_BASE_DIR"/{{APPLICATION_PAYLOAD}}
