#!/bin/sh

APPIMAGE_RELATIVE_BASE_DIR=$(dirname "$0")
APPIMAGE_BASE_DIR=$(realpath "$APPIMAGE_RELATIVE_BASE_DIR")
export XDG_DATA_DIRS="$APPIMAGE_BASE_DIR/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export LD_LIBRARY_PATH="$APPIMAGE_BASE_DIR/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

exec "$APPIMAGE_BASE_DIR"/{{APPLICATION_PAYLOAD}}
